<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>La Patrona</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
<div class="container">
    <h1 class="game-title">La Patrona</h1>
    <div class="text-area" id="game-text">
        <p>Bem-vindo ao jogo La Patrona!</p>
        <p>YOLANDA GONZALEZ</p>
        <p>Durante uma de suas rotinas habituais no tráfico, Yolanda Gonzalez recebe uma proposta para contrabandear uma carga, o que exige que ela deixe a Colômbia e vá para outro país.</p>
        <p>Diante disso oferem a Yolanda: um MAREA, um MONZA, um MAVERICK.</p>
    </div>
    <div class="input-area">
        <label for="command-input">Digite seu comando:</label>
        <input type="text" id="command-input" name="comando" placeholder="Digite seu comando aqui..">
        <button id="send-button">Enviar</button>
    </div>
    <main>
        <div class="console-box">
            <p><?= htmlspecialchars($arrayAssociativo->mensagem) ?></p>
        </div>
        <div class="form-group">
            <form method="get" action="">
                <input type="text" name="comando"/>
                <input type="text" name="save" value="<?= htmlspecialchars($arrayAssociativo->idSave) ?>" readonly/>
                <input type="submit"/>
            </form>
        </div>
    </main>
</div>
<script src="script.js"></script>
</body>
</html>
